FROM base/archlinux:2015.06.01
MAINTAINER kurotokiya <kurotokiya@gmail.com>

# Initialize the environment
RUN pacman -Syyu --noconfirm
RUN pacman -S --noconfirm shadowsocks-libev

EXPOSE 12345
CMD ["ss-server -c /config.json"]
